import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Orbitron } from "next/font/google";
import "./globals.css";
import { LedgerProvider } from "./components/Provider";
import { MintedPlayersProvider } from "./lib/minted-players-context";
import { VerificationProvider } from "./lib/verification-context";
import { Navbar } from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-pixel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <LedgerProvider>
        <MintedPlayersProvider>
          <VerificationProvider>
            <Navbar />
            <body
              className={`${inter.className} ${orbitron.variable} bg-zinc-950 text-zinc-100 min-h-screen mt-16`}
            >
              {children}
            </body>
          </VerificationProvider>
        </MintedPlayersProvider>
      </LedgerProvider>
    </html>
  );
}
